sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
before_script:
  - bundle exec rake compile
script:
  - bundle exec rake
  # The CSV tests in test/ are specific to Ruby 2.1.0.
  - if [ $TRAVIS_RUBY_VERSION = '2.1.0' ]; then bundle exec rspec test/runner.rb test/csv; fi
