language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - rake compile
script:
  - rake
  # The CSV tests in test/ are specific to Ruby 2.1.0.
  - if [ $TRAVIS_RUBY_VERSION = '2.1.0' ]; then rspec test/runner.rb test/csv; fi
