name: Branch Checks

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.version }}

      - name: Compile the extension
        run: bundle exec rake compile

      - name: Run tests
        run: bundle exec rspec
